version: '3.9'

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: turborepo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql 

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080